name: Nomad

# The workflow triggered by any change in deployments/nomad/.
# 1. Run nomad test.

on:
  pull_request:
    paths:
      - 'deployments/nomad/**'
      - '.github/workflows/nomad.yml'
      - '!**.md'

permissions:
  contents: write

defaults:
  run:
    working-directory: 'deployments/nomad'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nomad: [ "1.6.2-1", "1.7.5-1" ]
      fail-fast: false
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install Nomad and Consul.
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install nomad=${{ matrix.nomad }}
          sudo apt-get install consul

      - name: Validate otel-agent.nomad
        run: nomad job validate otel-agent.nomad

      - name: Validate otel-gateway.nomad
        run: nomad job validate otel-gateway.nomad

      - name: Start Nomad Service.
        run: |
          sudo touch /etc/systemd/system/nomad.service
          sudo echo "
          [Unit]
          Description=Nomad
          Documentation=https://www.nomadproject.io/docs/
          Wants=network-online.target
          After=network-online.target

          [Service]
          ExecReload=/bin/kill -HUP $MAINPID
          ExecStart=/usr/bin/nomad agent -dev
          KillMode=process
          KillSignal=SIGINT
          LimitNOFILE=65536
          LimitNPROC=infinity
          Restart=on-failure
          RestartSec=2

          TasksMax=infinity
          OOMScoreAdjust=-1000

          [Install]
          WantedBy=multi-user.target
          " >> nomad.service
          sudo mv nomad.service /etc/systemd/system/nomad.service
          sudo systemctl enable nomad
          sudo systemctl start nomad
          sudo systemctl status nomad
          a=0
          while [ "$a" -lt 10 ];
          do
            if [ $(sudo systemctl is-active nomad.service) == "active" ];
            then 
              echo "Nomad service is running.";
              break;
            else 
              sleep 10;
            fi
            a=`expr $a + 1`
          done
          if [ "$a" -eq 10 ];
          then
            echo "Fail to start Nomad service";
            sudo systemctl disable nomad;
            sudo systemctl stop nomad;
            sudo rm /etc/systemd/system/nomad.service;
            exit 1;
          fi

      - name: Start Consul Service.
        run: |
          sudo touch /etc/systemd/system/consul.service
          sudo echo "
          [Unit]
          Description=Consul
          Documentation=https://www.consul.io/docs
          Wants=network-online.target
          After=network-online.target

          [Service]
          ExecReload=/bin/kill -HUP $MAINPID
          ExecStart=/usr/bin/consul agent -dev
          KillMode=process
          KillSignal=SIGINT
          LimitNOFILE=65536
          LimitNPROC=infinity
          Restart=on-failure
          RestartSec=2

          TasksMax=infinity
          OOMScoreAdjust=-1000

          [Install]
          WantedBy=multi-user.target
          " >> consul.service
          sudo mv consul.service /etc/systemd/system/consul.service
          sudo systemctl enable consul
          sudo systemctl start consul
          a=0
          while [ "$a" -lt 10 ];
          do
            if [ $(sudo systemctl is-active consul.service) == "active" ];
            then 
              echo "Consul service is running.";
              break;
            else 
              sleep 10;
            fi
            a=`expr $a + 1`
          done
          if [ "$a" -eq 10 ];
          then
            echo "Fail to start Consul service";
            sudo systemctl disable consul;
            sudo systemctl stop consul;
            sudo rm /etc/systemd/system/consul.service;
            exit 1;
          fi
      - name: Prepare deployment
        run: |
          sed -i 's/<SPLUNK_ACCESS_TOKEN>/12345/g' otel-agent.nomad
          sed -i 's/<SPLUNK_REALM>/test/g' otel-agent.nomad
          sed -i 's/<SPLUNK_ACCESS_TOKEN>/12345/g' otel-gateway.nomad
          sed -i 's/<SPLUNK_REALM>/test/g' otel-gateway.nomad
          touch config.yaml

      - name: Deploy gateway with Nomad
        uses: qazz92/nomad-deploy-action@1.0.1
        with:
          token: ""
          address: http://localhost:4646
          job: otel-gateway.nomad
          config: config.yaml

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: http://localhost:4646
          nomad-token: ""
          nomad-job-name: otel-gateway.nomad
      - name: Stop gateway
        run: |
          nomad job stop -purge otel-gateway
          
      - name: Deploy agent with Nomad
        uses: qazz92/nomad-deploy-action@1.0.1
        with:
          token: ""
          address: http://localhost:4646
          job: otel-agent.nomad
          config: config.yaml

      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: http://localhost:4646
          nomad-token: ""
          nomad-job-name: otel-agent.nomad
      - name: Stop agent
        run: |
          nomad job stop -purge otel-agent

      - name: Stop Nomad and Consul Services.
        run: |
          sudo systemctl disable nomad
          sudo systemctl stop nomad
          sudo rm /etc/systemd/system/nomad.service
          sudo apt-get remove nomad
          sudo systemctl disable consul
          sudo systemctl stop consul
          sudo rm /etc/systemd/system/consul.service
          sudo apt-get remove consul
